- name: Deploy Kafka
  hosts: localhost
  tasks:
    - name: Download kafka tarball
      ansible.builtin.get_url:
        url: 'https://downloads.apache.org/kafka/3.7.0/kafka-3.7.0-src.tgz'
        dest: ./kafka-3.7.0-src.tgz

    - name: Untar tarball
      ansible.builtin.unarchive:
        src: ./kafka-3.7.0-src.tgz
        dest: ./
    - name: Install Java JRE
      ansible.builtin.apt:
        name: default-jre
